### ISSUE TITLE
Unhandled exception in physical_or_virtual.py

### ISSUE THREAD

**Issue by gregneagle** [munki/munki-facts#3]
Running this on my Late 2016 13" MacBook Pro with an active Ethernet interface on a connected Thunderbolt hub (IE not built-in):

```
Traceback (most recent call last):
  File "facts/physical_or_virtual.py", line 30, in <module>
    print fact()
  File "facts/physical_or_virtual.py", line 15, in fact
    ethernet_vid = plist[0]['_items'][0]['spethernet_vendor-id']
KeyError: 'spethernet_vendor-id'
```

If we print plist[0]['_items'][0] before line 15:

```
{'spusbethernet_PID': '34304', 'spethernet_BSD_Name': 'en5', 'spethernet_BUNDLE_IDentifier': 'AppleUSBNCM.kext', 'spethernet_version': '5.0.0', 'spethernet_device_type': 'USB', '_name': 'iBridge', 'spusbethernet_VID': '1452', 'spethernet_kext_path': '/System/Library/Extensions/AppleUSBNCM.kext', 'spusbethernet_mac_address': 're:da:ct:ed:11:22'}
```

**Comment by gregneagle** [comment]
Ping @erikng

**Comment by natewalck** [comment]
@gregneagle He is occupied with family stuff at the moment, just FYI.

**Comment by gregneagle** [comment]
It's certainly not an emergency!
